name: test docker
on: [push]
jobs:
  test-sigstore:
    permissions:
      contents: read
      packages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: sigstore/cosign-installer@v4.0.0
      - uses: docker/build-push-action@v6
        id: build-push-action
        with:
          push: true
          tags: "ghcr.io/turcking/workflow-test:latest"
          labels: "org.opencontainers.image.source=https://github.com/Turcking/workflow_test"
      - uses: actions/attest-build-provenance@v3
        with:
          subject-name: "ghcr.io/turcking/workflow-test"
          subject-digest: ${{ steps.build-push-action.outputs.digest }}
          push-to-registry: true
